[package]
name = "analyzer-app"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
analyzer-core = { path = "../analyzer-core" }
anyhow.workspace = true
serde_json.workspace = true
toml.workspace = true
tempfile.workspace = true
rusqlite = { version = "0.40.2", features = ["bundled", "backup", "hooks"] }
uuid = { version = "1.27.0", features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
